name: Style, Build and Docs
on: 
  push:
    branches:    
     - 'main'
    tags:
      - '*'
  pull_request:

jobs:
  make_docs:
    runs-on: ubuntu-latest
    name: Doc Builder
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc rename latexmk

    - run: cd docs && make

    - uses: actions/upload-artifact@v2
      with:
        name: AB_Docs
        path: docs/_build/pdf/*.pdf
  
  make_instructions:
    runs-on: ubuntu-latest
    name: Instruction Builder
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc rename latexmk

    - name: Install requirements
      run: pip install -r docs/requirements.txt

    - run: cd docs && make latexpdf

    - run: mv docs/_build/latex/mobiledeliverysystem.pdf docs/_build/latex/MDS_Operator_Manual.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: MDS_Instruction_Manual
        path: docs/_build/latex/MDS_Operator_Manual.pdf

  make_bin:
    runs-on: ubuntu-latest
    name: Binary Builder
    steps:
    - uses: actions/checkout@v2

    - run: cd arduino/mds && make bin

    - uses: actions/upload-artifact@v2
      with:
        name: AB-Transport_Arduino_Binaries
        path: arduino/mds/_build/arduino.avr.mega/*
  
  make_lint:
    runs-on: ubuntu-latest
    name: c++ Delinter
    steps:
    - uses: actions/checkout@v2

    - run: touch arduino/mds/README.md
    - run: touch arduino/mds/COPYING

    - run: cd arduino/mds && make lint

  publish_docs:
    # Only publish on tags
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    name: Create Brightspace Submission
    needs: [make_docs, make_bin, make_instructions]

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: AB_Docs

    - uses: actions/download-artifact@v2
      with:
        name: AB-Transport_Arduino_Binaries
        path: arduino_bin
  
    - uses: actions/download-artifact@v2
      with:
        name: MDS_Instruction_Manual

    - uses: papeloto/action-zip@v1
      with:
        files: arduino_bin/
        dest: arduino_binaries.zip

    - name: Upload Docs to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '*.pdf'
        tag: ${{ github.ref }}
        overwrite: true
        body: "A-B Transport EG-110, Automated with auto uploaded binaries."
        file_glob: true
    
    - name: Upload Binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: 'arduino_binaries.zip'
        tag: ${{ github.ref }}
        overwrite: true
